### PR TITLE
Make some hostapd params optional

### PR DESCRIPTION
**Pull request by kiurchv**

### CODE REVIEW

**Comment by sdelrio** [comment]
Could you write an explanation of the changes?

Why remove default values for  $DIVER and $HT_CAPAB?

**Comment by kiurchv** [comment]
Not all WiFi chips 802.11n capable and compatible with the nl80211 driver. Also in some cases, there is no need to specify driver at all. All these cases apply to Raspberry Pi 3 Model B built-in WiFi.

**Comment by sdelrio** [comment]
Ok, I will try to test with RPI3 this night.

Meanwhile, you could make some changes (if I don't find them later I will commit changes myself):

1.  Make the `apk update` on the same apk line so Docker doesn't create another later:

```
  RUN apk update && apk add bash hostapd iptables dhcp
```

2. Group and comment 802.11n and 802.11ac options, something like this:

```
# Activate channel selection for HT High Througput (802.11an) 
${HT_ENABLED+"ieee80211n=1"}
${HT_CAPAB+"ht_capab=${HT_CAPAB}"}

# Activate channel selection for VHT Very High Througput (802.11ac) 
${VHT_ENABLED+"ieee80211ac=1"}
${VHT_CAPAB+"vht_capab=${VHT_CAPAB}"}
```

Anyway, if I PR after test

**Comment by sdelrio** [comment]
I make the PR but will also make the commented changes. and a default working config at least for the integrated Pi wifi.

**Pull request merged**
